### ISSUE TITLE
server thread and sync thread go nuts when doing the job 

### ISSUE THREAD

**Issue by SKITTLE6969** [Randolio/randol_burgershot#1]
These two Wait(0) makes server thread and sync thread go nuts when doing the job 

https://github.com/Randolio/randol_burgershot/blob/c440a3f71a73f8ce7453643a46701f13929d9df5/randol_burgershot/client/cl_burgershot.lua#L47
https://github.com/Randolio/randol_burgershot/blob/c440a3f71a73f8ce7453643a46701f13929d9df5/randol_burgershot/client/cl_burgershot.lua#L72

**Comment by SKITTLE6969** [comment]
> These two Wait(0) makes server thread and sync thread go nuts when doing the job
> 
> https://github.com/Randolio/randol_burgershot/blob/c440a3f71a73f8ce7453643a46701f13929d9df5/randol_burgershot/client/cl_burgershot.lua#L47
> 
> 
> https://github.com/Randolio/randol_burgershot/blob/c440a3f71a73f8ce7453643a46701f13929d9df5/randol_burgershot/client/cl_burgershot.lua#L72

probably the first one i made it wait(1000)

**Comment by Randolio** [comment]
Thats just a you problem broski, runs at 0.00ms for me

**Comment by SKITTLE6969** [comment]
ill try adding a fresh copy
