### ISSUE TITLE
QBCore:Server:SetMetaData

### ISSUE THREAD

**Issue by wessleym** [Randolio/randol_burgershot#2]
Thank you for this resource.
Your code calls `TriggerServerEvent("QBCore:Server:SetMetaData" ... ` on this line
https://github.com/Randolio/randol_burgershot/blob/dfed48a22eb785126399dfdf8e92df766ae058a4/randol_burgershot/client/cl_consumables.lua#L17

and on this line
https://github.com/Randolio/randol_burgershot/blob/dfed48a22eb785126399dfdf8e92df766ae058a4/randol_burgershot/client/cl_consumables.lua#L32

According to this thread, this server event is deprecated:
https://github.com/qbcore-framework/qb-core/issues/910

Therefore, when eating food, hunger and thirst are not improved.  I wanted to make you aware of this so you could hopefully fix the code.  I'm not sure exactly what to do, but I have asked in the above thread about how to convert such code.  Thank you.

**Comment by Randolio** [comment]
I know how to fix it, i just never changed it because the majority of people were too scared to update their cores so i used old functions.
